# yaml-language-server: $schema=https://kubernetesjsonschema.dev/v1.18.1-standalone-strict/secret-v1.json
apiVersion: v1
kind: Secret
metadata:
  name: cloudflared-secret
stringData:
  credentials.json: ENC[AES256_GCM,data:0FRZeljxB2GbO0ty5DXyTciXcIyRVpLR2hQaU4URcHypxNWxar0LLElgoOApoQzLpqeekuIXrOsfyq3JzjHYj+Lpul/fDmi90MtuKM3q61C0nb/UwppWMBumhELaVExwUugcJRFFMGxPBOKd+1NaIyLCrKTkfqIMGNLVEendPD7HLCN4HPrAtbxyW1KO2oS6jPAT5oON76yyv/vjdMDsN7EbDkhEEoIYsGk5m0J6XA==,iv:fSFZOPxSLjGmtLyojYBY9k63GCIWxaCQiKVyIOOKA0U=,tag:/UsCgzOWKvL0Jx8TXJ7sIg==,type:str]
sops:
  kms: []
  gcp_kms: []
  azure_kv: []
  hc_vault: []
  age:
    - recipient: age15unrh656n4wza3n567h5s5mlym4jm7scju2dpmxzt0dqzwlmzemqsspey2
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB1ei9LV2NidjlERUVrSlda
        M216TmZXVjZrTDFseVM3VHlhS3JvMlVDMW5zCkVKNTlqY3pVcExSMWRnRUcxUjhC
        VG13T3U5ZHNXV0NOa2x2aks0OXdSVUEKLS0tIE5DVDQzSWZ6MDlwWTdZcHRlUi82
        RWFrbEFWaVZtMHJtZTlYRUNVckFNQU0KHfsz0KeUT8J+zcYdB6zwOW/xpitcTwyb
        K+rhdQw1kgId7jbeLApHU29IZvxxkhv4NUsusj0DUJjClY5G+w8rOA==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-03-01T02:56:38Z"
  mac: ENC[AES256_GCM,data:NQ/wPPBjlBS1MFU478JOuenQuUWENLekmjUIQQFa/3JoapnLZTx842p+6/x50jQ/jSW3tM4KTQSrbH2x4SErjRw64lhSnjFpOf+/erH3zzDhGXPmYArS74SbEckXuyuwF2sNgzWhKEq0EHUPbWXuser8fj8O6nwnXTqZE4ah7hY=,iv:Q5pBSD/dqLrlwkTKE21pz8ucAlCNPxVZTws7iS/9dQQ=,tag:EE30OpU1bmVZJIHZhKEVSQ==,type:str]
  pgp: []
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.9.4
