# yaml-language-server: $schema=https://kubernetesjsonschema.dev/v1.18.1-standalone-strict/secret-v1.json
apiVersion: v1
kind: Secret
metadata:
  name: cloudflared-secret
stringData:
  credentials.json: ENC[AES256_GCM,data:GkzuvR8glCkm5fFPEEx+qIclJ0fz16UyqWh8dtLtfOlJEO1KYZeIIsYbwsU3nM88Mq0Y5/c2YjP43tdKgh9F0uEig3cOXTNl49TXtN0bGGFr+bajTM7S82OHie3zrZ2NMuWEaBFU7F8qBMeSHu0tMOtGHbo7ANWMAzvzg2JZHwONU0Sn8vRMEncwdcAHwxxRWGYY7vG6GacKhm0aOQQAhSOpw6dOkT5Ul4SWeXRyYg==,iv:NM+EZ6SEWoiyifJAFIc+ICQkat+g7UE01hJxov+nu0I=,tag:SvEHaq8uzz7kjY3X4cOg5A==,type:str]
sops:
  kms: []
  gcp_kms: []
  azure_kv: []
  hc_vault: []
  age:
    - recipient: age15unrh656n4wza3n567h5s5mlym4jm7scju2dpmxzt0dqzwlmzemqsspey2
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBRc2E1cEJ4dmNpWmhDOFVr
        anlLSyt4SHpYZUZFLzZLSmZjOFNrQ1R0MXhnClhLMW1pN04rUnBzeTEvZGtpd0tP
        KzJTYk90UzRzU2d0L1NiNHhXYWRhRkUKLS0tIGxacUdaemxzMmxCQU9XTGwrbzNO
        ek4rZVdUQkVNT2ZHS1BZemEwOUVTblkKrqZNMPv13Ja1HJJy1J4tZnPzn+c5tHLu
        T8fvX/1RNuUMiLoIw+bzwvcIgzHbohhl79mosLuLvdlDmiVr2t9G2w==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-02-28T08:19:11Z"
  mac: ENC[AES256_GCM,data:Ui7akjsJtvy93mUK7ZzJmjQirt8C6o9MsmCErQIblQ/tWuLo7O092Fi8FnMvXAJAnQVeMig+cqcc2n9J9K4UIDYPbJONzW5mQv4zZk66n+0TGVYDNvcRETzzlTBuYplvL0eLcITFNwYWih6ZsLpGZl7hTW+oJ+/t6RHVIlKF1/I=,iv:R8azxNPw+edFvYgChVSai+vGsbLwmVOjSZYcb8Ttlyo=,tag:EHVgPBlVaVHfj/+UqdNIeQ==,type:str]
  pgp: []
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.9.4
