# yaml-language-server: $schema=https://kubernetesjsonschema.dev/v1.18.1-standalone-strict/secret-v1.json
apiVersion: v1
kind: Secret
metadata:
  name: cloudflared-secret
stringData:
  credentials.json: ENC[AES256_GCM,data:pKW397ZrZxSu+wOtuZwcy37wHgZbwgtAPL23F7zwk5+oB+S7oW1iWC7BwjCc7CjjktyE+uUcSPYCSIShrBrlXiGR0ttF2oJROgNA3tzq+15ALqQSnB5S2GkorFMadSpTDkVov8HwkwF+Ugr4AvHdytCrEByrnRiq8PYxtArBt1Gvque2h5PS8f9sSd91vjVaMAC986s6RoR2eBUS9ALx+H4ZT+yfHRD8Q0tERQxHRA==,iv:F10WS2ygLPP8RxKxEEdY6p7GBP9cStwCeH0x/AjiQGY=,tag:jvJxBp6q7k3pLCqviR9s6w==,type:str]
sops:
  kms: []
  gcp_kms: []
  azure_kv: []
  hc_vault: []
  age:
    - recipient: age15unrh656n4wza3n567h5s5mlym4jm7scju2dpmxzt0dqzwlmzemqsspey2
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBqODA3ZG0zRWFmRkE0QVpr
        UWE5Y2NkNWNqcUpHcVZtVEZFdGF3cGoraUZVCnBQVGRQSktMczQxRVQxQ2hvWUxF
        SGdtNG1pcXNjeXludHIzck9MV3hJV1kKLS0tIGpqZlk5elMzR2tJUWRTQSs5M1ow
        NHNRV0FnR1JxSTA5MnU1R3MwemxUSkUKYROJXamC/AWV+sE5W2FyLhvQw+hz+uae
        snyRRCNOyd5N26uHvVDdZgkstRKpPK+SWkM/LvtRtoqQ4EQO+h3jkQ==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-03-02T02:56:52Z"
  mac: ENC[AES256_GCM,data:plIAa0+Kq4oP0MEIss4EOSd2C7YH7x76gJiFrGnBfNTiKycvmdqIqiAwlb/5aZ0Fq3SAz27d2Gvkh+ybBLHN60f7UDLvL5d+KQ52W3gDkiJ/+4YMp3sKqws8FfPd0o0piHlLPZyAEIlzcgs1pxLpL469v0TO5E5RgzARQs87nYI=,iv:edWNHln8+4p5ZhqGjkuwxz+qafEmCRZXbun0TgBKhCw=,tag:5kXknpTG2d8CAiJQwfstYA==,type:str]
  pgp: []
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.9.4
