---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/apps.emqx.io/emqx_v2beta1.json
apiVersion: apps.emqx.io/v2beta1
kind: EMQX
metadata:
  name: emqx
spec:
  image: public.ecr.aws/emqx/emqx:5.8.8
  config:
    data: |
      authentication {
        backend = "built_in_database"
        mechanism = "password_based"
        password_hash_algorithm {
            name = "bcrypt"
        }
        user_id_type = "username"
        bootstrap_file = "/opt/init-user.json"
        bootstrap_type = "plain"
      }
      authorization {
        sources = [
          {
            type = built_in_database
            enable = true
          }
        ]
        no_match: "deny"
      }
  coreTemplate:
    metadata:
      annotations:
        reloader.stakater.com/auto: "true"
    spec:
      replicas: 2
      env:
        - name: EMQX_DASHBOARD__DEFAULT_USERNAME
          value: ${USERNAME}
        - name: EMQX_DASHBOARD__DEFAULT_PASSWORD
          value: ${EMQX_DASHBOARD_PASSWORD}
      extraVolumeMounts:
        - name: init-user
          mountPath: /opt/init-user.json
          subPath: init-user.json
          readOnly: true
      extraVolumes:
        - name: init-user
          configMap:
            name: emqx-init-user-config
  listenersServiceTemplate:
    metadata:
      annotations:
        external-dns.alpha.kubernetes.io/hostname: "mqtt.${SECRET_DOMAIN}"
        lbipam.cilium.io/ips: ${IP_EMQX}
    spec:
      type: LoadBalancer
