---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: apiservice
  labels:
    app: apiservice
spec:
  minReadySeconds: 60
  replicas: 1
  selector:
    matchLabels:
      app: apiservice
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: apiservice
    spec:
      imagePullSecrets:
        - name: registry-secret
      containers:
        - name: apiservice
          image: ${SECRET_REGISTRY}/apiservice:latest
          imagePullPolicy: Always
          ports:
            - name: http
              containerPort: 8080
            - name: https
              containerPort: 8443
          envFrom:
            - configMapRef:
                name: apiservice-env
          resources:
            requests:
              memory: "128Mi"
              cpu: "250m"
            limits:
              memory: "256Mi"
              cpu: "500m"
      terminationGracePeriodSeconds: 180
---
apiVersion: v1
kind: Service
metadata:
  name: apiservice
spec:
  type: ClusterIP
  selector:
    app: apiservice
  ports:
    - name: http
      port: 8080
      targetPort: 8080
    - name: https
      port: 8443
      targetPort: 8443
