# yaml-language-server: $schema=https://kubernetesjsonschema.dev/v1.18.1-standalone-strict/secret-v1.json
apiVersion: v1
kind: Secret
metadata:
  name: github-webhook-token-secret
stringData:
  token: ENC[AES256_GCM,data:tkyfxDE+mitC/k0qjFWVKC4sJhPoF5l+fedehkJ6zY4=,iv:QsjY7iAxXftB0XgtOFstlLtPJwOhUCanLVLYJy6yX6g=,tag:hJfuvpAE+3c4VgExzveo8g==,type:str]
sops:
  kms: []
  gcp_kms: []
  azure_kv: []
  hc_vault: []
  age:
    - recipient: age15unrh656n4wza3n567h5s5mlym4jm7scju2dpmxzt0dqzwlmzemqsspey2
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB4ekdoUVc4aVJpTHQzU1Nl
        U0d4YUYwclN0UkRveTlVUmtyNEN5Y2YvQmhjCkE5MWJjZnhQSUFyQm44emRiYVc1
        YWlWa3B4ZmRzclhsL0hWNEllNFlUVWcKLS0tICsyTjRwaEZkWDVXeHdGOHVOQmlz
        aWpSbEwvNHR3WWFYM1I5NlA5Tkt1SjAKLJDvv/t0i3UKOR816lSibGkGYNbFw/ei
        QGh3K4qhH7oVOfWqki913+2IdC6bag9PcLJ/0FY2HBmt04/yuLaO8g==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-03-01T02:56:38Z"
  mac: ENC[AES256_GCM,data:G2qQAo+QfJ29Xj81J/nyTxAv/ZIec5NRdsBC7fm61xcnDEfRYu/YrexQFM+PTgtO1qP/luXddWXw0sYrMw/ALc6IrmpMgTMnhPjYdHn2g6nKEelxrAXxZU1t1OfMn0CKrB0o4xOdAbtLEytCHQ4Okk9qYqfuzX04vAqqXLRmv3Y=,iv:FKXxK+inrss84hvXsWPmRs43bjwqqaxU9a6evc98atQ=,tag:oG75KsrVI8FVrQDBwn/jdA==,type:str]
  pgp: []
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.9.4
