apiVersion: v1
kind: Secret
metadata:
  name: postgres-superuser-secret
  labels:
    cnpg.io/reload: "true"
type: Opaque
stringData:
  username: postgres
  password: ${POSTGRES_PASSWORD}
  azureConnectionString: ${BACKUP_CONNECTION_STRING}
