---
# yaml-language-server: $schema=https://json.schemastore.org/kustomization
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: default
components:
  - ../../components/common
  - ../../components/repos/app-template
resources:
  - ./echo/ks.yaml
  - ./home-assistant/ks.yaml
  - ./emqx/ks.yaml
  - ./zigbee2mqtt/ks.yaml
  - ./zwave-js-ui/ks.yaml
  - ./bank/ks.yaml
  # - ./headlamp/ks.yaml
  - ./piggybank/ks.yaml
