---
# yaml-language-server: $schema=https://raw.githubusercontent.com/fluxcd-community/flux2-schemas/main/helmrelease-helm-v2.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: &app bank
spec:
  interval: 30m
  chartRef:
    kind: OCIRepository
    name: app-template
  install:
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      strategy: rollback
      retries: 3
  dependsOn:
    - name: cloudflared
      namespace: network
  values:
    controllers:
      *app :
        strategy: RollingUpdate
        annotations:
          reloader.stakater.com/auto: "true"
        containers:
          app:
            image:
              repository: nginx
              tag: 1.25.4-alpine
            env:
              PORT: &port 80
            probes:
              liveness: &probes
                enabled: true
                custom: true
                spec:
                  httpGet:
                    path: /
                    port: *port
                  initialDelaySeconds: 0
                  periodSeconds: 10
                  timeoutSeconds: 1
                  failureThreshold: 3
              readiness: *probes
            securityContext:
              allowPrivilegeEscalation: false
              readOnlyRootFilesystem: false
              capabilities: { drop: ["ALL"] }
            resources:
              requests:
                cpu: 10m
                memory: 32Mi
              limits:
                memory: 64Mi
    defaultPodOptions:
      securityContext:
        runAsNonRoot: true
        runAsUser: 101
        runAsGroup: 101
        fsGroup: 101
        seccompProfile: { type: RuntimeDefault }
    service:
      app:
        controller: *app
        ports:
          http:
            port: *port
    ingress:
      app:
        className: internal
        annotations:
          external-dns.alpha.kubernetes.io/target: "internal.${SECRET_DOMAIN}"
        hosts:
          - host: "{{ .Release.Name }}.${SECRET_DOMAIN}"
            paths:
              - path: /
                service:
                  identifier: app
                  port: http
    persistence:
      content:
        type: configMap
        name: content
        globalMounts:
          - path: /usr/share/nginx/html/index.html
            subPath: content/index.html
            readOnly: true
          - path: /usr/share/nginx/html/styles.css
            subPath: content/styles.css
            readOnly: true
          - path: /usr/share/nginx/html/script.js
            subPath: content/script.js
            readOnly: true
          - path: /usr/share/nginx/html/transactions.json
            subPath: content/transactions.json
            readOnly: true
      nginx-cache:
        type: emptyDir
        globalMounts:
          - path: /var/cache/nginx
      nginx-tmp:
        type: emptyDir
        globalMounts:
          - path: /tmp
      nginx-run:
        type: emptyDir
        globalMounts:
          - path: /var/run
