---
# yaml-language-server: $schema=https://json.schemastore.org/kustomization
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ./helmrelease.yaml

configMapGenerator:
  - name: content
    files:
      - index.html=./content/index.html
      - styles.css=./content/styles.css
      - script.js=./content/script.js
      - transactions.json=./content/transactions.json

generatorOptions:
  disableNameSuffixHash: true
