---
# yaml-language-server: $schema=https://json.schemastore.org/kustomization
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ./helmrelease.yaml

configMapGenerator:
  - name: content
    files:
      - ./content/index.html
      - ./content/styles.css
      - ./content/script.js
      - ./content/transactions.json

generatorOptions:
  disableNameSuffixHash: true
