apiVersion: v1
kind: Secret
metadata:
  name: cluster-secrets
stringData:
  SECRET_DOMAIN: ENC[AES256_GCM,data:RobKUwc580JvZYk=,iv:81L8MbyWNYcDcRp2S+pNDZzm/TzyND4SmSVssc45tck=,tag:Fu/IbXG6pKQJGwf4CIpQrQ==,type:str]
  TIMEZONE: ENC[AES256_GCM,data:q6pjpRKuJvRVmA1dClzqnjGldg==,iv:9/cOhdR0gjceYAPSvOzz9agzGEgGMUzs29WYW+HujQ0=,tag:tdUPoDWzskO+OkhNR43BmA==,type:str]
  ELEVATION: ENC[AES256_GCM,data:UQ==,iv:oeTfGgy9lBv1PkiGl0InLQk2BGr9slTA+uqIOZcVo7k=,tag:NayEvJE92O4B0Qy19F95yQ==,type:str]
  LATITUDE: ENC[AES256_GCM,data:/Q==,iv:qEHzV5mcJp7AXRpokZnaH6cQ5oLZXdgZGW1WdfBBQCQ=,tag:qgpfER4/n35CIHO177E4VQ==,type:str]
  LONGITUDE: ENC[AES256_GCM,data:aQ==,iv:U6SnHhDAgrWRzqqbsZ+ZsSznT9fGgeKcwzMYvFUcHGI=,tag:BtNG1WWMxhrlchl/Ho4BUA==,type:str]
  IP_EMQX: ENC[AES256_GCM,data:nNuBO8injV+K,iv:EzY/rfNtauaLUTp0tBUSniOuxrpoo042xBVXQvHt7Aw=,tag:s0RiY1YoprDw1a5/2lZeYA==,type:str]
sops:
  kms: []
  gcp_kms: []
  azure_kv: []
  hc_vault: []
  age:
    - recipient: age15unrh656n4wza3n567h5s5mlym4jm7scju2dpmxzt0dqzwlmzemqsspey2
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBOSnJMMjJpZWJ4ZVZVWXRv
        SnorUDQ1aG43a3R5bkY4RUgxUkF4eGVGWlVjCnhCV0RnNEVIazJ2bGJXWVRDL0pJ
        ZnlmbVpPN2ZzNFFheURLWHl4cXpyVm8KLS0tIDBrTVp0RVBXVWVYNWRNaWVnU1R2
        aXhUWldUMWdLVWp3SzBzelllQy93MWsK2rc3tDG9e7iw5YpvixJa6giZpFKEyONM
        4YOPVExNZtPgrXvIaLN/raHSyZ98IbyGzElS0hEZdQo0IfM0x823xw==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-03-16T03:11:21Z"
  mac: ENC[AES256_GCM,data:+jGXUGh306TAtwsYTyeJ8vIzkypvT3/xfeOh9ExF46oY/aeAUTH1YYKsYIDcIHltgRRG5Vc4xIEt8NPCAmZJtR+FgQi7o4C5W3Ixyxd/P/mYf1cCNHxF9+2oRzkK8/nHskWzb8JIas/51w4m2A+Fg0vBevcUVxBXocE+EY3XpMM=,iv:1TR0YyrRtPkxso4cHSXygYgrPqpqZLRKJzT6ycDpnC0=,tag:J7uliGVzr8L6rGkOv4MTeg==,type:str]
  pgp: []
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.9.4
