apiVersion: v1
kind: Secret
metadata:
  name: cluster-secrets
stringData:
  SECRET_DOMAIN: ENC[AES256_GCM,data:vx2JFAaS5E8diPg=,iv:rAmGlEoSJdJxtIwj2CKlnkb0PgwbXaT98cDuDpT3xF0=,tag:UAdKAoJxLKZc4Qa7Aaehwg==,type:str]
sops:
  kms: []
  gcp_kms: []
  azure_kv: []
  hc_vault: []
  age:
    - recipient: age15unrh656n4wza3n567h5s5mlym4jm7scju2dpmxzt0dqzwlmzemqsspey2
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBzZkxkL2dJZDdFYkJoKzRB
        YWJ0eWt2bjVXY3BrZ3VmeUp3dy9RU3lFSUZRCm9DYm11R3ZuVEJsdk5STWk2Q2lw
        RXc3eDFRRzNsNlRuQ3JVYzB1QzdwYTgKLS0tIE5iMHFyUkpUV3diZEhlK0w1RTRQ
        SFA3WWFGMnlZbXlRMngxbkJuWUhiaUEKkLEQlkH8muSKAbcFAdQMLPcR/qQN/gZR
        I1Wl17iMI2PFBqtAIY0WQnKDoEJuRX09+vQo5exfkysooWSDp1JZmA==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-03-01T02:56:38Z"
  mac: ENC[AES256_GCM,data:022WFvg1CpK32B5PyrDhTSE7R6slGRY2TAagLCy0JgDdlyqPtoIGmFk8gw+Rg+L7Qw2g65Fyvr8eQAAZJv5gQXWwqBLqSldvCUGTOPN+mu76tr5UC0gUKs1cvGCztrEVHZ4BKRXUgTwpUguZzge1TntY3CYbrOF8WopGktf8sEU=,iv:DOgCO//yHnVmgILj5T4hxJMV+OCUmRL42SQCb97ba4o=,tag:t/k+uGti/kJaV23/GiwRVA==,type:str]
  pgp: []
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.9.4
