apiVersion: v1
kind: Secret
metadata:
  name: sops-age
stringData:
  age.agekey: ENC[AES256_GCM,data:Xui8sdbsRqWLKffpjCtxL1kRXisMWT1roi1WXNkqCMw9vAy1tGUb8a5Z/YrFeqI+N1tlznQ2CSztCL1EO6iUeubBAqwEWyvitjU=,iv:J50jZbxmOCLZMYLWKpxPfh9dzoVAy5/vTMpB9kR8awM=,tag:7gwrS4/mUyNsOLI6E/pq6g==,type:str]
sops:
  kms: []
  gcp_kms: []
  azure_kv: []
  hc_vault: []
  age:
    - recipient: age15unrh656n4wza3n567h5s5mlym4jm7scju2dpmxzt0dqzwlmzemqsspey2
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBSSnB4TWFiWjJtVm9PK3pq
        TVJmKzNHY3NLZXRnRmxNeVZxbjRKV2xMMFFzCkNvblRTUEh0WUtWbUlhWEpFK2R1
        bEYxdDJiU096L0dPVTg0eFVxUVBBVG8KLS0tIHdkcUMyelNOQjJyMmFoWGZtckJ1
        RFkxOE5uNUFDMXFBcFE4Njc0b3c5S0UKu4+NkZivInou1r1cZeQfes7cD1iKgS6R
        Z6gm3S9tSZkgJ8ws+jfhdDlF8dfPLuht3G49jH0hopem58yvf3rW3Q==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-03-02T02:56:52Z"
  mac: ENC[AES256_GCM,data:jWq8CZai6B7k3WjPAv+DDhK6KhJeM2vP+iFKuDaoLpON5H/0qsS1kiIHHCA8v2I9BewcCdOTytn+TdSzOgLZ9CKN7cpzn+3D3T9znBRnodbBqBz0Dn6Isjzgv6WsKD1D7xcQq0trcLDb4F7t9j9vC2wHjIfYB66/+14IXbD/KVA=,iv:idlUM/g0ZucMDAxpncQF43okMAJu8Il3CnsYPgOIuz4=,tag:MjhYPw0jsli0M9JDKAytlQ==,type:str]
  pgp: []
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.9.4
