# yaml-language-server: $schema=https://kubernetesjsonschema.dev/v1.18.1-standalone-strict/secret-v1.json
apiVersion: v1
kind: Secret
metadata:
  name: cert-manager-secret
stringData:
  api-token: ENC[AES256_GCM,data:hmoEMFzgKRbEGJPGAZoRilGvWg/Y9W6bJWggNlbcKazxlEUjCX4NQg==,iv:iD65yyoZMZ21qmbbVqP4UnipF60XHiuY17hxzLUq4Dg=,tag:2HVcEPwPXwdjjomKO2h+Eg==,type:str]
sops:
  kms: []
  gcp_kms: []
  azure_kv: []
  hc_vault: []
  age:
    - recipient: age15unrh656n4wza3n567h5s5mlym4jm7scju2dpmxzt0dqzwlmzemqsspey2
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBmUWx4MDJFNlFnLzhJTG1q
        TkZhVnVZOVFVUjFpMDNUYXhUSU5EVndpMkdBCmg4K1VOQUd6ejhRbDhNc1RMdGlu
        QXlaU2JEemdZbFZxOEZKWkh5ZXAxZDQKLS0tIHRvRy9LOTlCNE00Z3JwRkJLOEgw
        MzlKZTRXNnhkYjMrdnBtZWcwMlRwNk0KdjW7mq7Esy7WyzY8V6TnJNZLOnoBjoc2
        HifTYw2HMP/m++jnkUPaE6S+Y5FQNX+u4uLZ51fOR2pujI2ASEo15Q==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-03-16T03:11:20Z"
  mac: ENC[AES256_GCM,data:8SY5kqG73s/51G9+2rQJMzXxfUucAnTH7/hiqPtip4Yf8TVgOueIyvZPgwlxYyaONpf/wOaYjBZrUooLGXQXxcAAfUuiIkExD8UVo59Pp9WG6u/t2hWde6Hyrf+ToCePsfdBouABZnGhgK+/K9/gz5b8L7tcGYmtLxW7F4Y9GC0=,iv:BuysXiUwpyMxdJQChSIZKa+q5e2C+nuaLww1hHf4yPA=,tag:KuC+P0era/Nl/5d+2ZDGkw==,type:str]
  pgp: []
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.9.4
