# yaml-language-server: $schema=https://kubernetesjsonschema.dev/v1.18.1-standalone-strict/secret-v1.json
apiVersion: v1
kind: Secret
metadata:
  name: cert-manager-secret
stringData:
  api-token: ENC[AES256_GCM,data:mIyl/C2103xvrTcd55UezOih2qtYnKOj0t4u/EhYdwF1s0RB04z/sQ==,iv:dSmf8V1N7qRxwSzg9crk4EZnahMc0I2rr0b5nTep9v4=,tag:Dg5/UICzln2+uVO9Yre6Ig==,type:str]
sops:
  kms: []
  gcp_kms: []
  azure_kv: []
  hc_vault: []
  age:
    - recipient: age15unrh656n4wza3n567h5s5mlym4jm7scju2dpmxzt0dqzwlmzemqsspey2
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBERHYybVpJcHBBb002anVH
        WjkwcHhId1dLRWZCUjlrcmFWYkk2cmF6M0RnCkNJa1ByNEJzRFV5RWxNVDA2TlI3
        VGxHeHdnMzhKZlNxWkk1Y0VZbEFsTWcKLS0tIHFqWWM1TUN2VkQrcTA5MkRRb1Mr
        VU9kMHI5RlBMcU10THRXenAxL3ZCcUEKGt25Dsnad71g+5Uyv7L61K1zNXcQ6306
        gqUKj5wOSp2usNP5StK53iknSNUUkmB6ytHv9QFD4L7Ykl5UdBm99w==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-03-02T02:56:52Z"
  mac: ENC[AES256_GCM,data:HmlcmZ9WJaT6WrrIgEfE5+clQT1M+NCJc2ZwD20VkELNDzpW29LF3PlPWX/5pJIehbnm0NQ9WcircKuGcA2x/sK5Rzf0KZM9jYnXFEHekkEcpzYikxSc/7rmdDFeSkRa2vKKdRVMp7+u1cl7IVJq8vvI4n57Zl1+kwxcXTdU0TQ=,iv:4UuRHAnEhQTR4xIIIwCLt8MhMhIiBMdJARhicTADtGM=,tag:Lcy5X5pwmzQWeaRAmNRlTg==,type:str]
  pgp: []
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.9.4
