---
# yaml-language-server: $schema=https://kube-schemas.pages.dev/helm.toolkit.fluxcd.io/helmrelease_v2.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: &app headlamp
spec:
  interval: 30m
  chart:
    spec:
      chart: headlamp
      version: 0.30.1
      sourceRef:
        kind: HelmRepository
        name: headlamp
        namespace: flux-system
  driftDetection:
    mode: enabled
  install:
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      strategy: rollback
      retries: 3
  values:
    fullnameOverride: *app
    podAnnotations:
      reloader.stakater.com/auto: "true"
    initContainers:
      - image: ghcr.io/headlamp-k8s/headlamp-plugin-flux:v0.2.0@sha256:6727bb58c95feef9f62f8fe125c244601d31ca62eab546b0f88c045560ed33de
        command:
          - /bin/sh
          - -c
          - mkdir -p /build/plugins && cp -r /plugins/* /build/plugins/
        name: headlamp-plugins
        volumeMounts:
          - mountPath: /build/plugins
            name: headlamp-plugins
    config:
      oidc:
        secret:
          create: true
      pluginsDir: /build/plugins
    extraManifests:
      - |
        apiVersion: v1
        kind: Secret
        type: kubernetes.io/service-account-token
        metadata:
          name: {{ include "headlamp.fullname" . }}-admin-token
          namespace: {{ .Release.Namespace }}
          annotations:
            kubernetes.io/service-account.name: {{ include "headlamp.serviceAccountName" . }}
    ingress:
      enabled: true
      annotations:
        external-dns.alpha.kubernetes.io/target: internal.${SECRET_DOMAIN}
      ingressClassName: internal
      hosts:
        - host: &host headlamp.${SECRET_DOMAIN}
          paths:
            - path: /
              type: ImplementationSpecific
              service:
                identifier: app
                port: http
      tls:
        - hosts:
            - *host

    volumeMounts:
      - mountPath: /build/plugins
        name: headlamp-plugins
    volumes:
      - name: headlamp-plugins
        persistentVolumeClaim:
          claimName: *app
